name: Build
on:
  workflow_dispatch:

env:
  CHANNEL_LINK: "pear://d5xqafujqx46hgeqeriuuyf1tdgxxgmdm9njijogrxcpc4exnkfy"
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
            tags: "v1"
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.tags }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: |  
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates build-essential git libgtk-4-dev pkg-config fuse file
          # sudo apt-get install -y clang pkg-config libgtk-4-dev clang-tools fuse file
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          npm install --global bare-make
          npm install --install-links --legacy-peer-deps
        if: ${{ matrix.platform == 'linux' }}

      - name: Build Linux AppImage
        run: |
          bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}
          bare-make build

      - name: Find & rename AppImage file
        id: find_file
        run: |
          set -euo pipefail
          APPIMAGE_PATH=$(find "$GITHUB_WORKSPACE" -name "*.AppImage" -type f | head -n 1)
          echo "Original AppImage: $APPIMAGE_PATH"

          NEW_NAME="Oniri-Desktop-Linux-${{ matrix.arch }}-${{ matrix.tags }}.AppImage"
          NEW_PATH="$GITHUB_WORKSPACE/$NEW_NAME"

          mv "$APPIMAGE_PATH" "$NEW_PATH"
          echo "Renamed AppImage to: $NEW_PATH"

          echo "APPIMAGE_PATH=$NEW_PATH" >> "$GITHUB_OUTPUT"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT
        if: ${{ matrix.platform == 'linux' }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.platform == 'linux' && steps.find_file.outputs.APPIMAGE_PATH != '' }}
        with:
          name: Oniri-Desktop-Linux-${{ matrix.arch }}-${{ matrix.tags }}.AppImage
          path: "${{ steps.find_file.outputs.APPIMAGE_PATH }}"

  merge:
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: install
          merge-multiple: true
      - uses: actions/upload-artifact@v4
        with:
          name: builds
          path: install
          retention-days: 1